### ISSUE TITLE
Failed Status check on the deployed lambda failed

### ISSUE THREAD

**Issue by dayolasode** [CiscoSecurity/tr-05-serverless-urlscanio#18]
python version: 3.7.8

On deploying the lambda for the urlscan.io, the below error is returned:

**Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.**

The status result is as below:

Status for tr-urlscanio-relay-dev:
        Lambda Versions:      2
        Lambda Name:          tr-urlscanio-relay-dev
        Lambda ARN:           arn:aws:lambda:eu-west-2:134225217845:function:tr-urlscanio-relay-dev
        Lambda Role ARN:      arn:aws:iam::134225217845:role/tr-serverless-relay-ZappaLambdaExecutionRole
        Lambda Handler:       handler.lambda_handler
        Lambda Code Size:     12654649
        Lambda Version:       $LATEST
        Lambda Last Modified: 2020-07-20T15:39:54.478+0000
        Lambda Memory Size:   512
        Lambda Timeout:       30
        Lambda Runtime:       python3.7
        Lambda VPC ID:        None
        Invocations (24h):    0
        Errors (24h):         0
        Error Rate (24h):     Error calculating
        API Gateway URL:      https://et5uuqdgv8.execute-api.eu-west-2.amazonaws.com/dev
        Domain URL:           None Supplied
        Num. Event Rules:     0

When accessed, the  API Gateway URL returns the below error :

`"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 540, in handler\\n    with Response.from_app(self.wsgi_app, environ) as response:\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 287, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 1119, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

This is the same error returned when the generated JWT is added to the cisco threat-response module

Also, tailing the zappa deployment log file throws up the  below messages:

(test) root@ansla02lv:~/mhayes# zappa tail dev
Calling tail for stage dev..
[1595250362642] Instancing..
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlockedmodule
[1595255989588] Instancing..
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlockedmodule
[1595258261750] Instancing..
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlockedmodule
[1595258666607] Instancing..
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlockedmodule
[1595258960784] 'NoneType' object is not callable
[1595259026723] 'NoneType' object is not callable
[1595259099368] 'NoneType' object is not callable
[1595259099386] 'NoneType' object is not callable
[1595259127550] 'NoneType' object is not callable
[1595259323661] 'NoneType' object is not callable
[1595259390333] 'NoneType' object is not callable
[1595259390584] 'NoneType' object is not callable
[1595259609930] Instancing..
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlockedmodule
[1595259702673] 'NoneType' object is not callable
[1595259723661] 'NoneType' object is not callable

Thanks

**Comment by maugertg** [comment]
This is the same error that is returned when trying to deploy without having first installed the requirements. As documented in the [AWS Common Errors guide](https://github.com/CiscoSecurity/tr-05-serverless-urlscanio/blob/develop/aws/CommonErrors.md#requirements-not-installed)

Please validate that you have followed the instructions in [Step 1](https://github.com/CiscoSecurity/tr-05-serverless-urlscanio#step-1-requirements-installation) and successfully executed 
```
pip install --upgrade --requirement requirements.txt
```

**Comment by dayolasode** [comment]
Please see the sequence of commands below. All the required libraries had already been installed but I re-installed again. The only differences are 

1) The AWS region. We are based in the UK so used region eu-west-2  
2) Using [pipenv](https://pypi.org/project/pipenv/) to create a virtual deployment environment

Not sure  any of the above makes any difference to deployment?

Thanks

```
root@ansla02lv:~/mhayes# aws configure get region --profile serverless
eu-west-2
root@ansla02lv:~/mhayes# python --version
Python 3.7.8
root@ansla02lv:~/mhayes# pip --version
pip 20.1.1 from /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages/pip (python 3.7)
root@ansla02lv:~/mhayes# cat reqs.txt
Authlib==0.14.3
Flask==1.1.2
marshmallow==3.6.1
requests==2.24.0
zappa==0.51.0
root@ansla02lv:~/mhayes# pip install --upgrade --requirement reqs.txt
Requirement already up-to-date: Authlib==0.14.3 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from -r reqs.txt (line 1)) (0.14.3)
Requirement already up-to-date: Flask==1.1.2 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from -r reqs.txt (line 2)) (1.1.2)
Requirement already up-to-date: marshmallow==3.6.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from -r reqs.txt (line 3)) (3.6.1)
Requirement already up-to-date: requests==2.24.0 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from -r reqs.txt (line 4)) (2.24.0)
Requirement already up-to-date: zappa==0.51.0 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from -r reqs.txt (line 5)) (0.51.0)
Requirement already satisfied, skipping upgrade: cryptography in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Authlib==0.14.3->-r reqs.txt (line 1)) (2.9.2)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.15 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Flask==1.1.2->-r reqs.txt (line 2)) (0.16.1)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Flask==1.1.2->-r reqs.txt (line 2)) (1.1.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Flask==1.1.2->-r reqs.txt (line 2)) (2.11.2)
Requirement already satisfied, skipping upgrade: click>=5.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Flask==1.1.2->-r reqs.txt (line 2)) (7.1.2)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from requests==2.24.0->-r reqs.txt (line 4)) (2.10)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from requests==2.24.0->-r reqs.txt (line 4)) (1.25.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from requests==2.24.0->-r reqs.txt (line 4)) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from requests==2.24.0->-r reqs.txt (line 4)) (2020.6.20)
Requirement already satisfied, skipping upgrade: durationpy in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.5)
Requirement already satisfied, skipping upgrade: pip>=9.0.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (20.1.1)
Requirement already satisfied, skipping upgrade: PyYAML in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (5.3.1)
Requirement already satisfied, skipping upgrade: jmespath in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.10.0)
Requirement already satisfied, skipping upgrade: hjson in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (3.0.1)
Requirement already satisfied, skipping upgrade: python-dateutil<2.7.0 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (2.6.1)
Requirement already satisfied, skipping upgrade: argcomplete in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (1.11.1)
Requirement already satisfied, skipping upgrade: wheel in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.34.2)
Requirement already satisfied, skipping upgrade: wsgi-request-logger in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.4.6)
Requirement already satisfied, skipping upgrade: kappa==0.6.0 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.6.0)
Requirement already satisfied, skipping upgrade: toml in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.10.1)
Requirement already satisfied, skipping upgrade: future in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (0.18.2)
Requirement already satisfied, skipping upgrade: six in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (1.15.0)
Requirement already satisfied, skipping upgrade: boto3 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (1.14.19)
Requirement already satisfied, skipping upgrade: python-slugify in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (4.0.1)
Requirement already satisfied, skipping upgrade: tqdm in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (4.47.0)
Requirement already satisfied, skipping upgrade: pip-tools in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (5.2.1)
Requirement already satisfied, skipping upgrade: troposphere in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from zappa==0.51.0->-r reqs.txt (line 5)) (2.6.1)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from cryptography->Authlib==0.14.3->-r reqs.txt (line 1)) (1.14.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask==1.1.2->-r reqs.txt (line 2)) (1.1.1)
Requirement already satisfied, skipping upgrade: importlib-metadata<2,>=0.23; python_version == "3.7" in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from argcomplete->zappa==0.51.0->-r reqs.txt (line 5)) (1.7.0)
Requirement already satisfied, skipping upgrade: placebo>=0.8.1 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from kappa==0.6.0->zappa==0.51.0->-r reqs.txt (line 5)) (0.9.0)
Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from boto3->zappa==0.51.0->-r reqs.txt (line 5)) (0.3.3)
Requirement already satisfied, skipping upgrade: botocore<1.18.0,>=1.17.19 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from boto3->zappa==0.51.0->-r reqs.txt (line 5)) (1.17.19)
Requirement already satisfied, skipping upgrade: text-unidecode>=1.3 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from python-slugify->zappa==0.51.0->-r reqs.txt (line 5)) (1.3)
Requirement already satisfied, skipping upgrade: cfn-flip>=1.0.2 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from troposphere->zappa==0.51.0->-r reqs.txt (line 5)) (1.2.3)
Requirement already satisfied, skipping upgrade: pycparser in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->Authlib==0.14.3->-r reqs.txt (line 1)) (2.20)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from importlib-metadata<2,>=0.23; python_version == "3.7"->argcomplete->zappa==0.51.0->-r reqs.txt (line 5)) (3.1.0)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /root/.local/share/virtualenvs/mhayes-Hwa1LcFS/lib/python3.7/site-packages (from botocore<1.18.0,>=1.17.19->boto3->zappa==0.51.0->-r reqs.txt (line 5)) (0.15.2)
(mhayes) root@ansla02lv:~/mhayes#
root@ansla02lv:~/mhayes# pip list | egrep -i "authlib|flask|marsh|request|zappa"
Authlib             0.14.3
Flask               1.1.2
marshmallow         3.6.1
requests            2.24.0
wsgi-request-logger 0.4.6
zappa               0.51.0
root@ansla02lv:~/mhayes# cat zappa_settings.json
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "eu-west-2",
        "exclude": [".*", "*.json", "*.md", "*.txt"],
        "keep_warm": false,
        "log_level": "INFO",
        "manage_roles": false,
        "profile_name": "serverless",
        "project_name": "tr-urlscanio-relay",
        "role_name": "tr-serverless-relay-ZappaLambdaExecutionRole",
        "runtime": "python3.7",
        "s3_bucket": "zappa-tr-urlscanio-relay-yodel-v2"
    }
}
root@ansla02lv:~/mhayes# zappa undeploy
Calling undeploy for stage dev..
Are you sure you want to undeploy? [y/n] y
Deleting API Gateway..
Waiting for stack tr-urlscanio-relay-dev to be deleted..
Unscheduling..
Deleting Lambda function..
Done!
root@ansla02lv:~/mhayes# zappa deploy
Calling deploy for stage dev..
Downloading and installing dependencies..
 - markupsafe==1.1.1: Downloading
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.5k/27.5k [00:00<00:00, 7.89MB/s]
 - cryptography==2.9.2: Using locally cached manylinux wheel
 - coverage==5.1: Using locally cached manylinux wheel
 - cffi==1.14.0: Using locally cached manylinux wheel
Packaging project as zip.
Uploading tr-urlscanio-relay-dev-1597057007.zip (12.1MiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.7M/12.7M [00:00<00:00, 31.5MB/s]
Uploading tr-urlscanio-relay-dev-template-1597057013.json (1.6KiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.65k/1.65k [00:00<00:00, 43.6kB/s]
Waiting for stack tr-urlscanio-relay-dev to create (this can take a bit)..
 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 3/4 [00:09<00:03,  3.07s/res]
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.
root@ansla02lv:~/mhayes#
```

**Comment by maugertg** [comment]
By using `pip` inside of an environment managed by `pipenv` you are negating some of the greatest benefits to using `pipenv` specifically the benefit of having a deterministic environment that is easily replicated using the `Pipfile.lock` file. Corey Schafer has a fantastic tutorial on using `pipenv` on YouTube [here](https://www.youtube.com/watch?v=zDYL22QNiWk)

The recommended method for installing packages into an environment that is managed by `pipenv` is:
```
pipenv install -r requirements.txt
```
Once the requirements are successfully installed in the virtual environment you can then use `run` to execute commands in the environment
```
pipenv run zappa deploy dev
```
or activate the environment and work within the interactive shell
```
pipenv shell
```
Start by creating a brand new virtual environment using the first command above. Using this sequence of commands I am able to create a new virtual environment with the requirements and deploy without issue. If you are unable to get this to work using `pipenv` I highly recommend you follow the provided instructions step by step in a fresh environment.

A note about your chosen region, as documented in the  [AWS HOWTO](https://github.com/CiscoSecurity/tr-05-serverless-urlscanio/blob/develop/aws/HOWTO.md#custom-aws-iam-users-and-policies-for-deployment) we recommend you use `eu-west-1` as it is the EU region that Threat Response is deployed in. 

> NOTE. Your AWS region should be geographically as close to your Threat Response region as possible to reduce latency as much as possible. The recommended AWS regions are:
>
> us-east-1 (for North America),
> eu-west-1 (for Europe),
> ap-northeast-1 (for Asia).
